# Generated by Django 5.2.4 on 2025-07-04 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=30)),
                ('age', models.PositiveIntegerField()),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('goals', models.JSONField(default=list)),
                ('join_date', models.DateField()),
                ('profile_image', models.URLField(blank=True, null=True)),
                ('subscription_type', models.CharField(blank=True, choices=[('standard', 'Standard'), ('premium', 'Premium'), ('personalized', 'Personalized')], max_length=20, null=True)),
                ('subscription_start', models.DateField(blank=True, null=True)),
                ('subscription_end', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('medical_conditions', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('muscle_groups', models.JSONField(default=list)),
                ('equipment', models.JSONField(default=list)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('instructions', models.JSONField(default=list)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('custom', 'Custom')], max_length=20)),
                ('days_per_week', models.PositiveIntegerField()),
                ('duration', models.PositiveIntegerField(help_text='Duration in weeks')),
                ('scheduled_days', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('estimated_duration', models.PositiveIntegerField()),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('category', models.CharField(choices=[('strength', 'Strength'), ('cardio', 'Cardio'), ('flexibility', 'Flexibility'), ('mixed', 'Mixed')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('target_value', models.FloatField()),
                ('current_value', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('deadline', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('weight', 'Weight'), ('strength', 'Strength'), ('endurance', 'Endurance'), ('flexibility', 'Flexibility'), ('custom', 'Custom')], max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.client')),
            ],
        ),
        migrations.CreateModel(
            name='ProgressMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight', models.FloatField()),
                ('body_fat', models.FloatField(blank=True, null=True)),
                ('muscle_mass', models.FloatField(blank=True, null=True)),
                ('measurements', models.JSONField(default=dict)),
                ('photos', models.JSONField(blank=True, default=list, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.client')),
            ],
        ),
        migrations.CreateModel(
            name='ClientRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_days', models.JSONField(default=list)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.client')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.routine')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='assigned_routines',
            field=models.ManyToManyField(blank=True, related_name='clients', to='gym.routine'),
        ),
        migrations.CreateModel(
            name='RoutineProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('rating', models.PositiveIntegerField(blank=True, null=True)),
                ('client_routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.clientroutine')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.workout')),
            ],
        ),
        migrations.AddField(
            model_name='routine',
            name='workouts',
            field=models.ManyToManyField(related_name='routines', to='gym.workout'),
        ),
        migrations.CreateModel(
            name='WorkoutSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.PositiveIntegerField()),
                ('weight', models.FloatField()),
                ('rest_time', models.PositiveIntegerField()),
                ('completed', models.BooleanField(default=False)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='gym.workout')),
            ],
        ),
    ]
