# Generated by Django 5.2.4 on 2025-07-05 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='assigned_routines',
        ),
        migrations.AlterField(
            model_name='clientroutine',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_routines', to='gym.client'),
        ),
    ]
