# Generated by Django 5.2.4 on 2025-07-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_client_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='age',
        ),
        migrations.AddField(
            model_name='client',
            name='birth_date',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
